export const CARD_DATA = [
  {
    id: "tutorial_1",
    character: "Adviser",
    role: "Chief of Staff",
    text: "My Lord, the people are restless. They demand a grand festival to celebrate your inauguration. It will cost us dearly, but it will secure their love.",
    leftChoice: "Host the festival!",
    rightChoice: "We cannot afford it.",
    leftEffect: { population: +20, treasury: -20, army: 0, religion: 0 },
    rightEffect: { population: -15, treasury: +10, army: 0, religion: 0 },
    leftNext: "tax_issue_1",
    rightNext: "military_issue_1",
  },
  {
    id: "tax_issue_1",
    character: "Treasurer",
    role: "Minister of Coin",
    text: "The treasury is draining faster than anticipated after the festival. We should raise taxes on the peasantry to recoup our losses.",
    leftChoice: "Tax the peasants.",
    rightChoice: "Tax the church instead.",
    leftEffect: { population: -20, treasury: +25, army: 0, religion: 0 },
    rightEffect: { population: 0, treasury: +20, army: 0, religion: -25 },
    leftNext: "military_issue_1",
    rightNext: "religion_issue_1",
  },
  {
    id: "military_issue_1",
    character: "General",
    role: "Commander of the Armies",
    text: "Our borders are weak, and the neighboring kingdom is amassing troops. We need funding to draft more soldiers immediately!",
    leftChoice: "Draft the peasants.",
    rightChoice: "We seek peace, not war.",
    leftEffect: { population: -15, treasury: -15, army: +30, religion: 0 },
    rightEffect: { population: +10, treasury: 0, army: -20, religion: 0 },
    leftNext: "religion_issue_1",
    rightNext: "foreign_threat_1",
  },
  {
    id: "religion_issue_1",
    character: "High Priest",
    role: "Voice of the Divine",
    text: "The gods demand a new grand cathedral to be built in the capital. It will bring divine favor to your reign, my Lord.",
    leftChoice: "Build the cathedral.",
    rightChoice: "The gods can wait.",
    leftEffect: { population: +5, treasury: -25, army: 0, religion: +30 },
    rightEffect: { population: 0, treasury: 0, army: 0, religion: -25 },
    leftNext: "random",
    rightNext: "random",
  },
  {
    id: "foreign_threat_1",
    character: "Ambassador",
    role: "Foreign Emissary",
    text: "The neighboring king offers an alliance, but demands we dismantle half of our standing army as a gesture of goodwill.",
    leftChoice: "Accept the alliance.",
    rightChoice: "Never. Prepare for war.",
    leftEffect: { population: +15, treasury: +10, army: -40, religion: 0 },
    rightEffect: { population: -10, treasury: -20, army: +20, religion: 0 },
    leftNext: "random",
    rightNext: "random",
  },
  {
    id: "plague_1",
    character: "Doctor",
    role: "Royal Physician",
    text: "A sickness is spreading through the lower districts. We must quarantine the sick, even if it requires force from the military.",
    leftChoice: "Quarantine them.",
    rightChoice: "Let it run its course.",
    leftEffect: { population: -10, treasury: 0, army: -10, religion: 0 },
    rightEffect: { population: -30, treasury: 0, army: 0, religion: -10 },
    leftNext: "random",
    rightNext: "random",
  },
];

export const DEATH_MESSAGES = {
  population_low: "The peasants dragged you from the palace and sent you to the guillotine. The revolution has begun.",
  population_high: "The people loved you so much they dissolved the monarchy and formed a republic. You are now a powerless figurehead.",
  treasury_low: "The kingdom went bankrupt. The palace was repossessed by foreign bankers, and you were sold into slavery.",
  treasury_high: "You hoarded so much wealth that the oligarchy poisoned your wine to seize the treasury for themselves.",
  army_low: "The neighboring empire marched across your undefended borders and claimed your throne.",
  army_high: "The military grew too powerful. The General staged a bloody coup and declared martial law.",
  religion_low: "The High Priest declared you a heretic. You were burned at the stake by zealots.",
  religion_high: "The Church seized total control of the state. You were forced to abdicate and become a silent monk.",
};
